#!/bin/bash
if [ "$#" -eq 0 ]; then
    echo >&2 "error: No file specified. Abort."
    exit 1
fi
if ! [ -f "$1" ]; then
    echo >&2 "error: '$1' does not exist. Abort."
    exit 1
fi
git diff HEAD -- "$1"
