#!/bin/bash
if ! command -v "xclip" >/dev/null 2>&1 ; then
	echo >&2 "error: xclip was not found. Abort."
	exit 1
fi
if [ "$#" -eq 0 ]; then
    echo >&2 "error: No file specified. Abort."
    exit 1
fi
if ! [ -f "$1" ] ; then
        echo >&2 "error: No such file. Abort."
	exit 1
fi
cat "$1" | tee >(xclip -selection clipboard) >(xclip -selection primary) >/dev/null;
