#!/bin/bash
if ! command -v "xclip" >/dev/null 2>&1 ; then
	echo >&2 "error: xclip was not found. Abort."
	exit 1
fi
echo -n "$PWD" | tee >(xclip -selection clipboard) >(xclip -selection primary) >/dev/null;
