#!/bin/bash
cmd="$(snippet "$@")"
echo "$cmd" >&2
echo "" >&2
while true; do
    echo         "--------------" >&2
    read -rn1 -p "Execute? [y/N] " answer
    echo >&2
    case "$answer" in
        y|Y) bash -c "$cmd"; break ;;
        ""|n|N)  echo "Aborted." >&2; break ;;
        *)   echo "Press 'y' to execute or Enter to abort." >&2 ;;
    esac
done
